# Use the base Ubuntu image
FROM ubuntu:latest

# Install MongoDB and other dependencies
RUN apt-get update && \
    apt-get install -y mongodb

# Expose the default MongoDB port
EXPOSE 27017

# Start MongoDB when the container starts
CMD ["mongod"]